Adding api for aggregator proxy
gamedoora/gamedoora-studio-services pull request #11
Opened 2023-10-08 15:09 UTC by picksitquick

Fixes #10 

## Proposed Changes

  - Added a new api to fetch user by Email Id
  - Using the updates Studio and StudioDTO Models.

2023-10-09 15:00 UTC, aprajshekhar requested changes
Overall, it looks good to me.  Just one suggestion.

2023-10-09 15:00 UTC, aprajshekhar commented on src/main/java/com/gamedoora/backend/studioservices/api/StudioServicesController.java
> +            value = "/users/{userEmail}",
The URL will be /users/email as the value of the email will be coming from the request param named email. To reduce the confusion, let's name the request param as emailId

2023-10-11 15:51 UTC, picksitquick commented
Sure, will update this. Also the build is failing, is it because of the token expiration?

2023-10-12 08:54 UTC, aprajshekhar commented
@picksitquick , there are no github actions for studio services. I am not sure which repo you are referring to?

2024-03-13 17:07 UTC, picksitquick commented
PR OUTDATED:
Will be raising a new PR as there are new changes as well.

2024-03-13 17:07 UTC, closed without merging